# Generated by Django 5.1.3 on 2024-12-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolemodel',
            name='unique_order',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='context',
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
