# Generated by Django 5.1.3 on 2024-12-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_gender_user_old_gender_user_geo_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='others', max_length=100),
            preserve_default=False,
        ),
    ]
