# Generated by Django 5.1.3 on 2024-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Non-binary')], default=None, null=True),
        ),
    ]
