# Generated by Django 5.1.3 on 2024-12-07 14:15

from django.db import migrations


def update_daily_rounds(apps, schema_editor):
    Notification = apps.get_model("facility", "Notification")
    DailyRound = apps.get_model("facility", "DailyRound")

    for notification in Notification.objects.all():

        if daily_round_id := notification.caused_objects.get("daily_round"):
            try:
                daily_round = DailyRound.objects.get(id=daily_round_id)
                notification.caused_objects["daily_round"] = str(daily_round.external_id)
                notification.save()
            except DailyRound.DoesNotExist:
                # Handle the case where the DailyRound does not exist
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.RunPython(update_daily_rounds),
    ]
