# Generated by Django 5.1.3 on 2024-12-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0468_remove_resourcerequest_assigned_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='category',
            field=models.IntegerField(choices=[(10, 'PATIENT_CARE'), (20, 'COMFORT_DEVICES'), (30, 'MEDICINES'), (40, 'FINANCIAL'), (100, 'OTHERS'), (200, 'SUPPLIES')], default=100),
        ),
    ]
