# Generated by Django 5.1.3 on 2024-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0469_alter_resourcerequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='is_antenatal',
            field=models.BooleanField(default=None, null=True, verbose_name='Does the patient require Prenatal Care ?'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='is_antenatal',
            field=models.BooleanField(default=None, null=True, verbose_name='Does the patient require Prenatal Care ?'),
        ),
    ]
