# Generated by Django 5.1.3 on 2024-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0470_alter_historicalpatientregistration_is_antenatal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
