# Generated by Django 5.1.3 on 2024-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0471_facility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientregistration',
            name='mobility_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INDEPENDENTLY_MOBILE', 'Independently Mobile'), ('INDEPENDENTLY_MOBILE_WITH_ILLNESS', 'Independently Mobile with Illness'), ('HOME_BOUND', 'Home Bound'), ('BED_BOUND', 'Bed Bound')], default='UNKNOWN', max_length=50, verbose_name='Mobility Status of Patient'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='mobility_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INDEPENDENTLY_MOBILE', 'Independently Mobile'), ('INDEPENDENTLY_MOBILE_WITH_ILLNESS', 'Independently Mobile with Illness'), ('HOME_BOUND', 'Home Bound'), ('BED_BOUND', 'Bed Bound')], default='UNKNOWN', max_length=50, verbose_name='Mobility Status of Patient'),
        ),
    ]
