# Generated by Django 5.1.3 on 2024-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0473_alter_facility_facility_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='category',
            field=models.CharField(blank=True, choices=[('Comfort', 'Comfort Care'), ('Stable', 'Mild'), ('Moderate', 'Moderate'), ('Critical', 'Critical'), ('ActivelyDying', 'Actively Dying')], max_length=13, null=True),
        ),
    ]
