# Generated by Django 5.1.3 on 2024-12-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0468_alter_facilitypatientstatshistory_unique_together_and_more'),
        ('facility', '0474_alter_patientconsultation_category'),
    ]

    operations = [
    ]
