# Generated by Django 5.1.3 on 2024-12-25 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0041_facilityorganization_metadata_organization_metadata'),
        ('facility', '0476_historicalpatientregistration_geo_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
