# Generated by Django 5.1.3 on 2024-12-26 13:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_questionnaire_internal_organization_cache_and_more'),
        ('facility', '0477_patientorganizations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientConsultationICMR',
        ),
        migrations.DeleteModel(
            name='PatientIcmr',
        ),
        migrations.DeleteModel(
            name='PatientSampleICMR',
        ),
        migrations.AddField(
            model_name='facility',
            name='default_internal_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_facilities', to='emr.facilityorganization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='geo_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.organization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='geo_organization_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='facility',
            name='internal_organization_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
