# Generated by Django 5.1.3 on 2024-12-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0478_delete_patientconsultationicmr_delete_patienticmr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsultationICMR',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientconsultation',),
        ),
        migrations.CreateModel(
            name='PatientIcmr',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientregistration',),
        ),
        migrations.CreateModel(
            name='PatientSampleICMR',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facility.patientsample',),
        ),
    ]
