# Generated by Django 5.1.3 on 2024-12-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0479_patientconsultationicmr_patienticmr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientOrganizations',
        ),
    ]
