# Generated by Django 5.1.3 on 2025-01-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0480_delete_patientorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
