# Generated by Django 5.1.1 on 2024-11-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyintolerance',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='allergyintolerance',
            name='code',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='allergyintolerance',
            name='onset',
            field=models.JSONField(default=dict),
        ),
    ]
