# Generated by Django 5.1.1 on 2024-11-16 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_allergyintolerance_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('compose', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=255)),
                ('is_system_defined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
