# Generated by Django 5.1.1 on 2024-11-28 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('subject_id', models.UUIDField()),
                ('subject_type', models.CharField(max_length=255)),
                ('responses', models.JSONField(default=dict)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
