# Generated by Django 5.1.1 on 2024-11-30 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_servicerequest'),
        ('facility', '0466_camera_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('accession_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('processing', models.JSONField(blank=True, default=list, null=True)),
                ('note', models.JSONField(blank=True, default=list, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.servicerequest')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
