# Generated by Django 5.1.1 on 2024-11-28 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_questionnaireresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='encounter',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=255)),
                ('category', models.JSONField(default=dict)),
                ('main_code', models.JSONField(default=dict)),
                ('alternate_coding', models.JSONField(default=list)),
                ('subject_type', models.CharField(max_length=255)),
                ('subject_id', models.UUIDField()),
                ('encounter', models.UUIDField()),
                ('effective_datetime', models.DateTimeField()),
                ('performer', models.JSONField(default=dict)),
                ('value', models.TextField()),
                ('value_code', models.JSONField(default=dict)),
                ('note', models.TextField()),
                ('body_site', models.JSONField(default=dict)),
                ('method', models.JSONField(default=dict)),
                ('reference_range', models.JSONField(default=list)),
                ('interpretation', models.CharField(max_length=255)),
                ('data_entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_entered', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.observation')),
                ('questionnaire_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaireresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
