# Generated by Django 5.1.1 on 2024-11-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_questionnaireresponse_encounter_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='subject_type',
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='responses',
            field=models.JSONField(default=list),
        ),
    ]
