# Generated by Django 5.1.1 on 2024-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_remove_questionnaireresponse_subject_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),

    ]
