# Generated by Django 5.1.1 on 2024-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_observation_is_group_alter_observation_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='parent',
        ),
    ]
