# Generated by Django 5.1.1 on 2024-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_remove_observation_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='parent',
            field=models.UUIDField(null=True),
        ),
    ]
