# Generated by Django 5.1.1 on 2024-12-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_remove_observation_encounter'),
        ('facility', '0466_camera_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='encounter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facility.patientconsultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration'),
            preserve_default=False,
        ),
    ]
