# Generated by Django 5.1.1 on 2024-12-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0013_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='patient',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
