# Generated by Django 5.1.1 on 2024-12-05 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0014_questionnaireresponse_patient'),
        ('facility', '0466_camera_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('status_changed', models.DateTimeField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('do_not_perform', models.BooleanField()),
                ('method', models.JSONField(blank=True, default=dict, null=True)),
                ('authored_on', models.DateTimeField(blank=True, null=True)),
                ('dosage_instruction', models.JSONField(blank=True, default=list, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientconsultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
