# Generated by Django 5.1.1 on 2024-12-05 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0015_medicationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
