# Generated by Django 5.1.1 on 2024-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0017_alter_questionnaire_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='value_code',
        ),
        migrations.AddField(
            model_name='observation',
            name='value_type',
            field=models.CharField(default='sdfsd', max_length=255),
            preserve_default=False,
        ),
    ]
