# Generated by Django 5.1.1 on 2024-12-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_specimen'),
        ('emr', '0017_alter_questionnaire_slug'),
    ]

    operations = [
    ]
