# Generated by Django 5.1.1 on 2024-12-08 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0018_merge_0006_specimen_0017_alter_questionnaire_slug'),
        ('facility', '0466_camera_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('code', models.JSONField(default=dict)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('effective_period', models.JSONField(blank=True, null=True)),
                ('media', models.JSONField(blank=True, default=list, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('note', models.JSONField(blank=True, default=list, null=True)),
                ('based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.servicerequest')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientconsultation')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ManyToManyField(blank=True, to='emr.observation')),
                ('results_interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specimen', models.ManyToManyField(blank=True, to='emr.specimen')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
