# Generated by Django 5.1.1 on 2024-12-08 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0019_diagnosticreport'),
        ('facility', '0466_camera_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_specimen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.specimen'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_specimen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='based_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='emr.servicerequest'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='facility.patientconsultation'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_diagnostic_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='result',
            field=models.ManyToManyField(blank=True, related_name='diagnostic_report', to='emr.observation'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='results_interpreter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpreted_diagnostic_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='specimen',
            field=models.ManyToManyField(blank=True, related_name='diagnostic_report', to='emr.specimen'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='facility.patientregistration'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='facility.patientconsultation'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_service_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='facility.patientregistration'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collected_specimen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='emr.servicerequest'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='facility.patientregistration'),
        ),
    ]
