# Generated by Django 5.1.3 on 2024-12-13 09:13

import django.db.models.deletion
from django.db import migrations, models


def delete_observations_questionnaires(apps, schema_editor):
    Observation = apps.get_model("emr", "Observation")
    QuestionnaireResponse = apps.get_model("emr", "QuestionnaireResponse")
    Observation.objects.all().delete()
    QuestionnaireResponse.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0020_facilityorganization'),
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.RunPython(delete_observations_questionnaires , reverse_code=migrations.RunPython.noop),
    ]
