# Generated by Django 5.1.3 on 2024-12-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0021_alter_questionnaireresponse_encounter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='patient',
        ),
    ]
