# Generated by Django 5.1.3 on 2024-12-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0022_remove_questionnaireresponse_encounter_and_more'),
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='encounter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facility.patientconsultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facility.patientregistration'),
            preserve_default=False,
        ),
    ]
