# Generated by Django 5.1.3 on 2024-12-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0024_allergyintolerance_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='structured_response_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='structured_responses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.questionnaire'),
        ),
    ]
