# Generated by Django 5.1.3 on 2024-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0026_schedulableresource_availabilityexception_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='slot_type',
            field=models.CharField(),
        ),
    ]
