# Generated by Django 5.1.3 on 2024-12-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0029_alter_tokenbooking_booked_by'),
        ('facility', '0470_alter_historicalpatientregistration_is_antenatal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.patientconsultation'),
        ),
    ]
