# Generated by Django 5.1.3 on 2024-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0031_medicationstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationstatement',
            name='information_source',
            field=models.CharField(max_length=100),
        ),
    ]
