# Generated by Django 5.1.3 on 2024-12-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0033_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenslot",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="availabilityexception",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="availabilityexception",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="availabilityexception",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="schedulableresource",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schedulableresource",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="schedulableresource",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="tokenslot",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="tokenbooking",
            name="booked_by",
        ),
        migrations.RemoveField(
            model_name="tokenbooking",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tokenbooking",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="tokenbooking",
            name="token_slot",
        ),
        migrations.RemoveField(
            model_name="tokenbooking",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="tokenslot",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tokenslot",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.DeleteModel(
            name="AvailabilityException",
        ),
        migrations.DeleteModel(
            name="SchedulableResource",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="TokenBooking",
        ),
        migrations.DeleteModel(
            name="TokenSlot",
        ),
    ]
