# Generated by Django 5.1.3 on 2024-12-27 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_medicationadministration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='occurrence_period',
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='occurrence_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='occurrence_period_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
