# Generated by Django 5.1.3 on 2024-12-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_remove_medicationadministration_occurrence_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationadministration',
            name='status_reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
