# Generated by Django 5.1.3 on 2024-12-24 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_organization_parent_cache_facilityorganizationuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityorganization',
            name='level_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilityorganization',
            name='parent_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='facilityorganization',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
