# Generated by Django 5.1.3 on 2024-12-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_schedulableuserresource_availabilityexception_and_more'),
        ('emr', '0036_facilityorganization_level_cache_and_more'),
    ]

    operations = [
    ]
