# Generated by Django 5.1.3 on 2024-12-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0037_merge_20241224_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='root_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='emr.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emr.organization'),
        ),
    ]
