# Generated by Django 5.1.3 on 2024-12-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0038_organization_root_org_alter_organization_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityorganization',
            name='root_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='emr.facilityorganization'),
        ),
        migrations.AlterField(
            model_name='facilityorganization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emr.facilityorganization'),
        ),
    ]
