# Generated by Django 5.1.3 on 2024-12-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0040_facilityorganization_has_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityorganization',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
