# Generated by Django 5.1.3 on 2024-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0041_facilityorganization_metadata_organization_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cached_parent_json',
            field=models.JSONField(default=dict),
        ),
    ]
