# Generated by Django 5.1.3 on 2024-12-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0042_organization_cached_parent_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityorganization',
            name='cached_parent_json',
            field=models.JSONField(default=dict),
        ),
    ]
