# Generated by Django 5.1.3 on 2024-12-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0036_alter_medicationadministration_status_reason'),
        ('emr', '0045_rename_dosage_medicationstatement_dosage_text'),
    ]

    operations = [
    ]
