# Generated by Django 5.1.3 on 2024-12-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0052_encounter_condition_allergyintolerance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='TokenBooking',
        ),
    ]
