# Generated by Django 5.1.3 on 2024-12-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0046_merge_20241227_1152'),
        ('emr', '0056_fileupload'),
    ]

    operations = [
    ]
