# Generated by Django 5.1.3 on 2024-12-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0057_merge_0046_merge_20241227_1152_0056_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationadministration',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient'),
        ),
    ]
