# Generated by Django 5.1.3 on 2024-12-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0058_alter_medicationadministration_encounter_and_more'),
        ('emr', '0058_resourcerequest_resourcerequestcomment'),
    ]

    operations = [
    ]
