# Generated by Django 5.1.3 on 2024-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_alter_medicationrequest_dosage_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrequest',
            name='dosage_instruction',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
