# Generated by Django 5.1.3 on 2024-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_merge_20241230_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='as_needed_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
